version: 2

models:
  - name: users
    description: One record per user
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: last_access_date
        description: Last access date
